mapa1 = [[False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]]
